#!/usr/bin/env php
<?php

set_time_limit(0);

$app = require_once __DIR__ ."/app/bootstrap.php";

$console = $app["console"];
$console->add(new Swaeg\Commands\CsvCommand());
$console->add(new Swaeg\Commands\ResetCommand());
$console->add(new Swaeg\Commands\InitCommand());
$console->run();
